language: python

python:
  - "2.7"
  - "3.2"

install:
    - "pip install --use-mirrors mock"
    - "pip install msgpack-python"
    - "pip install http://github.com/michalbachowski/pypromise/archive/1.0.3.zip#egg=PyPromise-1.0.3"

script: make test
